export const ContactMutations = {
  SET_LOADING: "LOADING_MUTATIONS_MUTATIONS",
  ADD_CONTACT: "ADD_CONTACT_MUTATIONS",
  DELETE_CONTACT: "DELETE_CONTACT_MUTATIONS",
  UPDATE_CONTACT: "UPDATE_CONTACT_MUTATIONS",
  LOAD_CONTACTS: "LOAD_CONTACTS_MUTATIONS",
  SET_USER_ID: "SET_USER_ID_MUTATIONS",
};

export const ContactActions = {
  SET_LOADING: "LOADING_ACTIONS_ACTIONS",
  ADD_CONTACT: "ADD_CONTACT_ACTIONS",
  DELETE_CONTACT: "DELETE_CONTACT_ACTIONS",
  UPDATE_CONTACT: "UPDATE_CONTACT_ACTIONS",
  LOAD_CONTACTS: "LOAD_CONTACTS_ACTIONS",
  SET_USER_ID: "SET_USER_ID_ACTIONS",
};

export const UserMutations = {
  SET_LOADING: "SET_LOADING_MUTATIONS",
  SET_USER_INFO: "SET_USER_INFO_MUTAtIONS",
  GET_USER_INFO: "GET_USER_INFO_MUTAtIONS",
  SET_USER_ID_EMAIL: "SET_USER_ID_EMAIL_MUTATIONS",
  SET_USER_PIC: "SET_USER_PIC_MUTATIONS",
  GET_USER_PIC: "GET_USER_PIC_MUTATIONS",
};

export const UserActions = {
  SET_LOADING: "SET_LOADING_ACTIONS",
  SET_USER_INFO: "SET_USER_INFO_ACTIONS",
  GET_USER_INFO: "GET_USER_INFO_ACTIONS",
  SET_USER_ID_EMAIL: "SET_USER_ID_EMAIL_ACTIONS",
  SET_USER_PIC: "SET_USER_PIC_ACTIONS",
  GET_USER_PIC: "GET_USER_PIC_ACTIONS",
};

export const SocketMutations = {
  WELCOME_MESSAGE: "WELCOME_MESSAGE_MUTATIONS",
  MESSAGE_NOTIFICATIONS: "MESSAGE_NOTIFICATIONS_MUTATIONS",
  GENERAL_NOTIFICATIONS: "GENERAL_NOTIFICATIONS_MUTATIONS",
  USER_TYPING: "USER_TYPING_MUTATIONS",
};

export const SocketActions = {
  CONNECTION: "CONNECTION_ACTIONS",
  WELCOME_MESSAGE: "WELCOME_MESSAGE_ACTIONS",
  MESSAGE_NOTIFICATIONS: "MESSAGE_NOTIFICATIONS_ACTIONS",
  GENERAL_NOTIFICATIONS: "GENERAL_NOTIFICATIONS_ACTIONS",
  USER_TYPING: "USER_TYPING_ACTIONS",
  STARTED_TYPING: "STARTED_TYPING_ACTION",
};
